### ISSUE TITLE
Event 1102 without UserData

### ISSUE THREAD

**Issue by massimiliano-dalcero** [sumeshi/evtx2es#12]
Hello :)

I'm using evtx2es for reading Securfity.evtx and I noticed that event 1102 doesn't have the EventData, especially username

![image](https://github.com/sumeshi/evtx2es/assets/5049867/0dfba34b-193d-4030-89de-5c4f0e162bec)

Using another (and oldest) project https://github.com/vavarachen/evtx2json I can find correctly username in UserData:

![image](https://github.com/sumeshi/evtx2es/assets/5049867/664d5328-c1a4-4727-8927-10ce835bd3db)

Compatible with the original Windows event viewer:

![image](https://github.com/sumeshi/evtx2es/assets/5049867/6af6f45a-e24b-46a5-a3a5-0ca407f03684)

![image](https://github.com/sumeshi/evtx2es/assets/5049867/da627f2b-e3b8-4322-bce1-237b06ce7482)

**Comment by sumeshi** [comment]
Hello.

Thank you for addressing the issue with event 1102!

I reviewed the PR, and as shown in the screenshots below, the username is now correctly included in EventData.

I've merged the changes and released it as v1.6.1. I really appreciate your support :)

![image](https://github.com/sumeshi/evtx2es/assets/35072092/b847284b-baab-4a08-8075-0f6eb0e007bd)
